#!/usr/bin/env python3
"""Deterministic governance decision packets for THF TokenOps blockers.

The packet factory turns dependency-free resolution work into review-only decision
forms. It deliberately leaves economic values and approvals unset. It never
creates Solana transactions/instructions, signatures, or binding financial acts.
"""
from __future__ import annotations

import hashlib
import json
from typing import Any, Dict, List

SCHEMA = "thf-tokenops-governance-decision-packets/v1"


def _sha256(value: Any) -> str:
    raw = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()
    return hashlib.sha256(raw).hexdigest()


def build_governance_decision_packets(dag: Dict[str, Any]) -> Dict[str, Any]:
    nodes = list(dag.get("nodes", []))
    packets: List[Dict[str, Any]] = []
    for node in sorted(nodes, key=lambda x: str(x.get("blocker"))):
        if not node.get("ready_for_resolution_work"):
            continue
        blocker = str(node.get("blocker"))
        required_fields = list(node.get("required_fields", []))
        packet = {
            "schema": "thf-tokenops-governance-decision-packet/v1",
            "blocker": blocker,
            "class": node.get("class"),
            "workstream": node.get("workstream"),
            "depends_on": list(node.get("depends_on", [])),
            "decision_status": "DRAFT_REQUIRED",
            "required_fields": required_fields,
            "decision_values": {field: None for field in required_fields},
            "review_requirements": {
                "requires_user_controlled_governance": bool(node.get("requires_user_controlled_governance")),
                "requires_public_evidence": bool(node.get("requires_public_evidence")),
                "immutable_evidence_sha256_required": any(str(f).endswith("_sha256") for f in required_fields),
                "economic_values_autoselected": False,
                "approval_autogenerated": False,
            },
            "execution": {
                "review_only": True,
                "execution_authorized": False,
                "transaction_bytes_created": False,
                "instruction_bytes_created": False,
                "signed": False,
                "submitted": False,
                "broadcast": False,
                "financial_effect": False,
                "private_key_required": False,
                "wave_touched": False,
            },
        }
        packet["packet_sha256"] = _sha256(packet)
        packets.append(packet)

    result = {
        "schema": SCHEMA,
        "network": dag.get("network"),
        "mint": dag.get("mint"),
        "resolution_dag_sha256": dag.get("resolution_dag_sha256"),
        "status": "REVIEW_INPUTS_REQUIRED" if packets else "NO_DEPENDENCY_FREE_DECISIONS",
        "packet_count": len(packets),
        "dependency_blocked_count": len(dag.get("dependency_blocked_resolution_work", [])),
        "packets": packets,
        "signer_action_now": "NONE",
        "execution_authorized": False,
        "transaction_bytes_created": False,
        "instruction_bytes_created": False,
        "signed": False,
        "submitted": False,
        "broadcast": False,
        "financial_effect": False,
        "wave_touched": False,
    }
    result["decision_packet_root_sha256"] = _sha256(result)
    return result


def validate_governance_decision_packets(bundle: Dict[str, Any]) -> List[str]:
    errors: List[str] = []
    if bundle.get("execution_authorized") is not False:
        errors.append("execution_authorized_must_be_false")
    for flag in ("transaction_bytes_created", "instruction_bytes_created", "signed", "submitted", "broadcast", "financial_effect", "wave_touched"):
        if bundle.get(flag) is not False:
            errors.append(f"unsafe_bundle_flag:{flag}")
    if bundle.get("signer_action_now") != "NONE":
        errors.append("signer_action_must_be_none")
    for packet in bundle.get("packets", []):
        if packet.get("decision_status") != "DRAFT_REQUIRED":
            errors.append(f"packet_not_draft:{packet.get('blocker')}")
        required = list(packet.get("required_fields", []))
        values = dict(packet.get("decision_values", {}))
        if sorted(required) != sorted(values):
            errors.append(f"decision_field_mismatch:{packet.get('blocker')}")
        if any(values.get(field) is not None for field in required):
            errors.append(f"autofilled_decision_value:{packet.get('blocker')}")
        execution = dict(packet.get("execution", {}))
        for flag in ("execution_authorized", "transaction_bytes_created", "instruction_bytes_created", "signed", "submitted", "broadcast", "financial_effect", "wave_touched"):
            if execution.get(flag) is not False:
                errors.append(f"unsafe_packet_flag:{packet.get('blocker')}:{flag}")
        if execution.get("private_key_required") is not False:
            errors.append(f"private_key_requirement:{packet.get('blocker')}")
    return sorted(errors)
